FROM public.ecr.aws/lambda/python:3.9

WORKDIR ${LAMBDA_TASK_ROOT}

RUN yum install -y git && yum clean all

COPY requirements-aws.txt .
RUN pip install --no-cache-dir -r requirements-aws.txt

COPY . .

ENV DJANGO_SETTINGS_MODULE=backend.settings.aws
ENV PYTHONUNBUFFERED=1

CMD ["lambda_handler.handler"]
